---
exclude: ^upstrean
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0 # or specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.21.0
      hooks:
          - id: pyupgrade
            args: [--py3-plus]
    - repo: https://github.com/psf/black
      rev: 21.6b0
      hooks:
          - id: black
