---
name: Release

on:
    schedule:
        - cron: 0 4 * * *
    workflow_dispatch:
        inputs:
            force:
                description: force build
                required: true
                type: boolean
                default: false

jobs:
    modify:
        name: Modifying source code
        runs-on: ubuntu-latest
        outputs:
            new_commits: ${{ steps.update.outputs.new_commits }}
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Update submodule
              continue-on-error: true
              id: update
              env:
                  FORCE_BUILD: ${{ github.event.inputs.force }}
              run: |
                  git submodule update --remote upstream
                  git config user.name "Sophie Keller"
                  git config user.email 90475612+skeller00@users.noreply.github.com
                  if git commit -am "Committing changes from upstream"; then
                    echo "new_commits=true" >> $GITHUB_OUTPUT
                    git push
                  else
                    echo "There are no new commits, I'll go back to sleep :sleeping:" >> $GITHUB_STEP_SUMMARY
                    echo "new_commits=$FORCE_BUILD" >> $GITHUB_OUTPUT
                  fi
            - name: Running modifications
              if: steps.update.outputs.new_commits == 'true'
              run: |
                  sed -i \
                    -e "s/version=version/version=\"$(date +%Y.%m.%d)\"/g" upstream/setup.py \
                  upstream/setup.py
                  sed -i \
                    -e "s/name = snowflake-connector-python/name= snowflake-connector-python-nightly/" \
                    -e "s/description = .*/description = Nigthly build of Snowflake Connector for Python/" \
                    -e "s/Source=.*/Source=https:\/\/github.com\/keller00\/snowflake-connector-python-nightlies\//" \
                  upstream/setup.cfg
            - uses: actions/upload-artifact@v2
              if: steps.update.outputs.new_commits == 'true'
              with:
                  name: modified_source
                  path: upstream
    build-sdist:
        name: Build sdist
        runs-on: ubuntu-latest
        needs: modify
        if: needs.modify.outputs.new_commits == 'true' && needs.modify.result == 'success'
        steps:
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.x
            - uses: actions/download-artifact@v3
              with:
                  name: modified_source
            - name: Build sdist
              run: python setup.py sdist
            - name: Show built sdist
              run: ls -lh dist
            - uses: actions/upload-artifact@v3
              with:
                  path: dist
                  name: sdist

    build-wheel:
        name: Build py${{ matrix.python }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        needs: modify
        if: needs.modify.outputs.new_commits == 'true' && needs.modify.result == 'success'
        defaults:
            run:
                shell: bash
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
                python: ['37', '38', '39', '310', '311']
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: modified_source
            - if: matrix.os == 'ubuntu-latest'
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: all
            - uses: pypa/cibuildwheel@v2.11.4
              env:
                  CIBW_SKIP: '*-musllinux*'
                  CIBW_BUILD: cp${{ matrix.python }}-*
                  CIBW_ARCHS_MACOS: x86_64 arm64 universal2
                  CIBW_ARCHS_WINDOWS: AMD64
                  CIBW_ARCHS_LINUX: x86_64 aarch64
                  MACOSX_DEPLOYMENT_TARGET: 10.14
              with:
                  output-dir: dist
            - name: Show built wheels
              run: ls -lh dist
            - uses: actions/upload-artifact@v3
              with:
                  path: dist
                  name: wheels
    release:
        name: Release built wheels
        runs-on: ubuntu-latest
        needs: [build-wheel, build-sdist]
        if: needs.build-wheel.result == 'success' && needs.build-sdist.result == 'success'
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: wheels
            - uses: actions/download-artifact@v3
              with:
                  name: sdist
            - name: Show all built wheels
              run: ls -lh .
            - name: Publish a Python distribution to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
                  packages-dir: .
